server:
  http:
    addr: 0.0.0.0:9001
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    username: ozline_a
    password: Mima011216
    address: db.ozline.icu
    port: 3306
    dbname: ozline_test
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
  snowflake:
    start_time: "2021-09-07"
    machine_id: 1
auth:
  secret: MTAxNTkwMTg1Mw==